# Generated by Django 5.2 on 2025-05-02 10:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_ru', models.CharField(max_length=500, null=True)),
                ('name_uz', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('address_ru', models.TextField(null=True)),
                ('address_uz', models.TextField(null=True)),
                ('telegram', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('whatsapp', models.CharField(max_length=500)),
                ('iframe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.about')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=500)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='main.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_ru', models.CharField(max_length=500, null=True)),
                ('name_uz', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', ckeditor.fields.RichTextField()),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('scope', ckeditor.fields.RichTextField()),
                ('scope_ru', ckeditor.fields.RichTextField(null=True)),
                ('scope_uz', ckeditor.fields.RichTextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('key_ru', models.CharField(max_length=500, null=True)),
                ('key_uz', models.CharField(max_length=500, null=True)),
                ('value', models.CharField(max_length=500)),
                ('value_ru', models.CharField(max_length=500, null=True)),
                ('value_uz', models.CharField(max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('color_ru', models.CharField(max_length=500, null=True)),
                ('color_uz', models.CharField(max_length=500, null=True)),
                ('in_package', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='main.product')),
            ],
        ),
    ]
