# Generated by Django 5.2 on 2025-05-12 07:59

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image2',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.FileField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(upload_to=utils.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=utils.generate_unique_filename),
        ),
    ]
